global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'prometheus-federation'
    consul_sd_configs:
    - server: '<server-2>:8500'
      services:
        - 'prometheus_federation'
    relabel_configs:         
    - source_labels: [__meta_consul_tags]
      regex: .*,_app=([^,]+),.*
      replacement: ${1}
      target_label: _app           
  - job_name: dc_prometheus
    honor_labels: true
    metrics_path: /federate
    params:
      match[]:
      - '{job="kubernetes-nodes-cadvisor"}'
    static_configs:
      - targets:
        - <server-1>:30909
# prometheus federation prometheus_build_info{_app="prometheus"}